version: 2

project_name: m3u8-downloader

builds:
  - id: cli-darwin-amd64
    binary: m3u8-downloader
    main: ./cmd/cli
    goos:
      - darwin
    goarch:
      - amd64
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}
    env:
      - CGO_ENABLED=0
      - MACOSX_DEPLOYMENT_TARGET=10.13

  - id: cli-darwin-arm64
    binary: m3u8-downloader
    main: ./cmd/cli
    goos:
      - darwin
    goarch:
      - arm64
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}
    env:
      - CGO_ENABLED=0

  - id: gui-darwin-amd64
    binary: m3u8-downloader-gui
    main: ./cmd/gui
    goos:
      - darwin
    goarch:
      - amd64
    env:
      - CGO_ENABLED=1
      - MACOSX_DEPLOYMENT_TARGET=10.13

  - id: gui-darwin-arm64
    binary: m3u8-downloader-gui
    main: ./cmd/gui
    goos:
      - darwin
    goarch:
      - arm64
    env:
      - CGO_ENABLED=1

archives:
  - id: m3u8-downloader
    ids:
      - cli-darwin-amd64
      - cli-darwin-arm64
      - gui-darwin-amd64
      - gui-darwin-arm64
    formats:
      - tar.gz
    name_template: "{{ .Os }}_{{ .Arch }}"
    files:
      - README.md

changelog:
  use: git
