version: 2

project_name: m3u8-downloader

builds:
  - id: cli
    binary: m3u8-downloader
    main: ./cmd/cli
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}
    env:
      - CGO_ENABLED=0

  - id: gui
    binary: m3u8-downloader-gui
    main: ./cmd/gui
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=1

archives:
  - id: m3u8-downloader
    ids:
      - cli
      - gui
    formats:
      - tar.gz
    name_template: "{{ .Os }}_{{ .Arch }}"
    files:
      - README.md

changelog:
  use: git
